module.exports = {
  ragnar: {
    basePath: '/',
    apiBasePath: '/promotions/api',
    server: {
      port: 8080,
      securePort: 8443,
      host: '0.0.0.0',
      static: './build',
    },
    middlewares: {
      platform: false,
      authenticate: false,
      // "device": false
    },
    version: require(`${__dirname}/../package.json`).version,
  },
  api: {
    internal: {
      baseUrl: 'http://internal-api.mercadolibre.com',
    },
    middleend: {
      url: siteId => `/seller-promotions/admin-middleend/sites/${siteId}/promotions`,
      uploadToBatchApi: `/seller-promotions/batch/files/pre-negotiated/process`,
      urlBatchApi: path => `/seller-promotions/batch/files/${path}`,
      urlBatchApiMassive: path => `/seller-promotions/batch/${path}`,
      urlItems: siteId => `/seller-promotions/admin-middleend/sites/${siteId}/items`,
      urlCredibilityExceptions: siteId => `/seller-promotions/admin-middleend/sites/${siteId}/credibility_whitelist`,
    },
  },
  i18n: {
    app: 'i18n-demo',
    srcPath: `${__dirname}/../app`,
  },
  odin: {
    // "adminId": "your-admin-id"
  },
  backToPreviousAdmin: false,
  country: {
    AR: {
      defaultSite: 'mla',
    },
    MX: {
      defaultSite: 'mlm',
    },
    BR: {
      defaultSite: 'mlb',
    },
    default: {
      defaultSite: 'mla',
    },
  },
  security: {
    mocked_user: {
      email: 'developer.local@mercadolibre.com',
      firstName: 'Developer',
      fullName: 'Developer Local',
      language: 'es',
      lastName: 'Local',
      locale: 'es',
      roles: ['SP_CENTRAL_FULL'],
      timeZone: 'GMT-3',
      userId: 'developerlocal',
      sessionId: 'devel-123123',
    },
    rolesMap: {
      SP_ADMIN_FULL: [
        'SP_CENTRAL_PROMOTION_LIST',
        'SP_CENTRAL_PROMOTION_CREATE',
        'SP_CENTRAL_PROMOTION_APPROVE',
        'SP_CENTRAL_PROMOTION_MODIFY',
        'SP_CENTRAL_PROMOTION_DELETE',
        'SP_CENTRAL_PROMOTION_FINISH',
        'SP_CENTRAL_PROMOTION_SIMULATE',
        'SP_CENTRAL_PROMOTION_OFFER_LIST',
        'SP_CENTRAL_PROMOTION_OFFER_COMPETENCE',
        'SP_CENTRAL_PROMOTION_OFFER_ADD',
        'SP_CENTRAL_PROMOTION_OFFER_REMOVE',
        'SP_CENTRAL_PROMOTION_OFFER_MODIFY',
        'SP_CENTRAL_PROMOTION_OFFER_CONFIRM',
        'SP_CENTRAL_PROMOTION_OFFER_APPROVE',
        'SP_CENTRAL_PROMOTION_OFFER_RISK_APPROVE',
        'SP_CENTRAL_PROMOTION_OFFER_EDIT',
        'SP_CENTRAL_PROMOTION_OFFER_DELETE',
        'SP_CENTRAL_PROMOTION_CREATE_CANDIDATE_OFFER',
        'SP_CENTRAL_PROMOTION_VIEW_CANDIDATE_OFFER',
        'SP_CENTRAL_PROMOTION_CREDIBILITY_EXCEPTIONS',
      ],
      SP_ADMIN_HEADCOM: [
        'SP_CENTRAL_PROMOTION_LIST',
        'SP_CENTRAL_PROMOTION_SIMULATE',
        'SP_CENTRAL_PROMOTION_CREATE',
        'SP_CENTRAL_PROMOTION_DELETE',
        'SP_CENTRAL_PROMOTION_FINISH',
        'SP_CENTRAL_PROMOTION_APPROVE',
        'SP_CENTRAL_PROMOTION_OFFER_LIST',
        'SP_CENTRAL_PROMOTION_OFFER_COMPETENCE',
        'SP_CENTRAL_PROMOTION_OFFER_ADD',
        'SP_CENTRAL_PROMOTION_OFFER_REMOVE',
        'SP_CENTRAL_PROMOTION_OFFER_MODIFY',
        'SP_CENTRAL_PROMOTION_OFFER_CONFIRM',
        'SP_CENTRAL_PROMOTION_OFFER_APPROVE',
        'SP_CENTRAL_PROMOTION_OFFER_EDIT',
        'SP_CENTRAL_PROMOTION_OFFER_DELETE',
        'SP_CENTRAL_PROMOTION_CREATE_CANDIDATE_OFFER',
        'SP_CENTRAL_PROMOTION_VIEW_CANDIDATE_OFFER',
        'SP_CENTRAL_PROMOTION_CREDIBILITY_EXCEPTIONS',
      ],
      SP_ADMIN_MKT: [
        'SP_CENTRAL_PROMOTION_LIST',
        'SP_CENTRAL_PROMOTION_SIMULATE',
        'SP_CENTRAL_PROMOTION_CREATE',
        'SP_CENTRAL_PROMOTION_DELETE',
        'SP_CENTRAL_PROMOTION_OFFER_LIST',
        'SP_CENTRAL_PROMOTION_OFFER_COMPETENCE',
        'SP_CENTRAL_PROMOTION_CREDIBILITY_EXCEPTIONS',
      ],
      SP_ADMIN_COM: [
        'SP_CENTRAL_PROMOTION_LIST',
        'SP_CENTRAL_PROMOTION_SIMULATE',
        'SP_CENTRAL_PROMOTION_CREATE',
        'SP_CENTRAL_PROMOTION_DELETE',
        'SP_CENTRAL_PROMOTION_OFFER_LIST',
        'SP_CENTRAL_PROMOTION_OFFER_COMPETENCE',
        'SP_CENTRAL_PROMOTION_OFFER_ADD',
        'SP_CENTRAL_PROMOTION_OFFER_REMOVE',
        'SP_CENTRAL_PROMOTION_OFFER_MODIFY',
        'SP_CENTRAL_PROMOTION_OFFER_CONFIRM',
        'SP_CENTRAL_PROMOTION_OFFER_EDIT',
        'SP_CENTRAL_PROMOTION_OFFER_DELETE',
        'SP_CENTRAL_PROMOTION_CREATE_CANDIDATE_OFFER',
        'SP_CENTRAL_PROMOTION_VIEW_CANDIDATE_OFFER',
        'SP_CENTRAL_PROMOTION_CREDIBILITY_EXCEPTIONS',
      ],
      SP_CENTRAL_FULL: [
        'SP_CENTRAL_PROMOTION_LIST',
        'SP_CENTRAL_PROMOTION_CREATE',
        'SP_CENTRAL_PROMOTION_APPROVE',
        'SP_CENTRAL_PROMOTION_MODIFY',
        'SP_CENTRAL_PROMOTION_DELETE',
        'SP_CENTRAL_PROMOTION_FINISH',
        'SP_CENTRAL_PROMOTION_SIMULATE',
        'SP_CENTRAL_PROMOTION_OFFER_LIST',
        'SP_CENTRAL_PROMOTION_OFFER_COMPETENCE',
        'SP_CENTRAL_PROMOTION_OFFER_ADD',
        'SP_CENTRAL_PROMOTION_OFFER_REMOVE',
        'SP_CENTRAL_PROMOTION_OFFER_MODIFY',
        'SP_CENTRAL_PROMOTION_OFFER_CONFIRM',
        'SP_CENTRAL_PROMOTION_OFFER_APPROVE',
        'SP_CENTRAL_PROMOTION_OFFER_RISK_APPROVE',
        'SP_CENTRAL_PROMOTION_OFFER_EDIT',
        'SP_CENTRAL_PROMOTION_OFFER_DELETE',
        'SP_CENTRAL_PROMOTION_CANDIDATES_ITEMS_LIST',
        'SP_CENTRAL_PROMOTION_CREATE_CANDIDATE_OFFER',
        'SP_CENTRAL_PROMOTION_VIEW_CANDIDATE_OFFER',
        'SP_CENTRAL_PROMOTION_CREDIBILITY_EXCEPTIONS',
      ],
      SP_CENTRAL_DEV: [
        'SP_CENTRAL_PROMOTION_LIST',
        'SP_CENTRAL_PROMOTION_CREATE',
        'SP_CENTRAL_PROMOTION_APPROVE',
        'SP_CENTRAL_PROMOTION_MODIFY',
        'SP_CENTRAL_PROMOTION_DELETE',
        'SP_CENTRAL_PROMOTION_FINISH',
        'SP_CENTRAL_PROMOTION_SIMULATE',
        'SP_CENTRAL_PROMOTION_OFFER_LIST',
        'SP_CENTRAL_PROMOTION_OFFER_COMPETENCE',
        'SP_CENTRAL_PROMOTION_OFFER_ADD',
        'SP_CENTRAL_PROMOTION_OFFER_REMOVE',
        'SP_CENTRAL_PROMOTION_OFFER_MODIFY',
        'SP_CENTRAL_PROMOTION_OFFER_CONFIRM',
        'SP_CENTRAL_PROMOTION_OFFER_APPROVE',
        'SP_CENTRAL_PROMOTION_OFFER_RISK_APPROVE',
        'SP_CENTRAL_PROMOTION_OFFER_EDIT',
        'SP_CENTRAL_PROMOTION_OFFER_DELETE',
        'SP_CENTRAL_PROMOTION_CANDIDATES_ITEMS_LIST',
        'SP_CENTRAL_PROMOTION_CREATE_CANDIDATE_OFFER',
        'SP_CENTRAL_PROMOTION_VIEW_CANDIDATE_OFFER',
        'SP_CENTRAL_PROMOTION_CREDIBILITY_EXCEPTIONS',
      ],
      SP_CENTRAL_LEAD: [
        'SP_CENTRAL_PROMOTION_LIST',
        'SP_CENTRAL_PROMOTION_CREATE',
        'SP_CENTRAL_PROMOTION_APPROVE',
        'SP_CENTRAL_PROMOTION_MODIFY',
        'SP_CENTRAL_PROMOTION_DELETE',
        'SP_CENTRAL_PROMOTION_FINISH',
        'SP_CENTRAL_PROMOTION_SIMULATE',
        'SP_CENTRAL_PROMOTION_OFFER_LIST',
        'SP_CENTRAL_PROMOTION_OFFER_COMPETENCE',
        'SP_CENTRAL_PROMOTION_OFFER_ADD',
        'SP_CENTRAL_PROMOTION_OFFER_REMOVE',
        'SP_CENTRAL_PROMOTION_OFFER_MODIFY',
        'SP_CENTRAL_PROMOTION_OFFER_CONFIRM',
        'SP_CENTRAL_PROMOTION_OFFER_APPROVE',
        'SP_CENTRAL_PROMOTION_OFFER_EDIT',
        'SP_CENTRAL_PROMOTION_OFFER_DELETE',
        'SP_CENTRAL_PROMOTION_OFFER_RISK_APPROVE',
        'SP_CENTRAL_PROMOTION_CREATE_CANDIDATE_OFFER',
        'SP_CENTRAL_PROMOTION_VIEW_CANDIDATE_OFFER',
        'SP_CENTRAL_PROMOTION_CREDIBILITY_EXCEPTIONS',
      ],
      SP_CENTRAL_HEADCOM: [
        'SP_CENTRAL_PROMOTION_LIST',
        'SP_CENTRAL_PROMOTION_SIMULATE',
        'SP_CENTRAL_PROMOTION_CREATE',
        'SP_CENTRAL_PROMOTION_DELETE',
        'SP_CENTRAL_PROMOTION_FINISH',
        'SP_CENTRAL_PROMOTION_APPROVE',
        'SP_CENTRAL_PROMOTION_OFFER_LIST',
        'SP_CENTRAL_PROMOTION_OFFER_COMPETENCE',
        'SP_CENTRAL_PROMOTION_OFFER_ADD',
        'SP_CENTRAL_PROMOTION_OFFER_REMOVE',
        'SP_CENTRAL_PROMOTION_OFFER_MODIFY',
        'SP_CENTRAL_PROMOTION_OFFER_CONFIRM',
        'SP_CENTRAL_PROMOTION_OFFER_APPROVE',
        'SP_CENTRAL_PROMOTION_OFFER_EDIT',
        'SP_CENTRAL_PROMOTION_OFFER_DELETE',
        'SP_CENTRAL_PROMOTION_CREATE_CANDIDATE_OFFER',
        'SP_CENTRAL_PROMOTION_VIEW_CANDIDATE_OFFER',
      ],
      SP_CENTRAL_MKT: [
        'SP_CENTRAL_PROMOTION_LIST',
        'SP_CENTRAL_PROMOTION_SIMULATE',
        'SP_CENTRAL_PROMOTION_CREATE',
        'SP_CENTRAL_PROMOTION_DELETE',
        'SP_CENTRAL_PROMOTION_OFFER_LIST',
        'SP_CENTRAL_PROMOTION_OFFER_COMPETENCE',
      ],
      SP_CENTRAL_COM: [
        'SP_CENTRAL_PROMOTION_LIST',
        'SP_CENTRAL_PROMOTION_SIMULATE',
        'SP_CENTRAL_PROMOTION_CREATE',
        'SP_CENTRAL_PROMOTION_DELETE',
        'SP_CENTRAL_PROMOTION_OFFER_LIST',
        'SP_CENTRAL_PROMOTION_OFFER_COMPETENCE',
        'SP_CENTRAL_PROMOTION_OFFER_ADD',
        'SP_CENTRAL_PROMOTION_OFFER_REMOVE',
        'SP_CENTRAL_PROMOTION_OFFER_MODIFY',
        'SP_CENTRAL_PROMOTION_OFFER_CONFIRM',
        'SP_CENTRAL_PROMOTION_OFFER_EDIT',
        'SP_CENTRAL_PROMOTION_OFFER_DELETE',
        'SP_CENTRAL_PROMOTION_CREATE_CANDIDATE_OFFER',
        'SP_CENTRAL_PROMOTION_VIEW_CANDIDATE_OFFER',
      ],
      SP_CENTRAL_TIERS: [
        'SP_CENTRAL_PROMOTION_LIST',
        'SP_CENTRAL_PROMOTION_SIMULATE',
        'SP_CENTRAL_PROMOTION_CREATE',
        'SP_CENTRAL_PROMOTION_DELETE',
        'SP_CENTRAL_PROMOTION_OFFER_LIST',
      ],
    },
    actionMap: {
      delete: ['SP_CENTRAL_PROMOTION_DELETE'],
      cancel: ['SP_CENTRAL_PROMOTION_FINISH'],
      approve: ['SP_CENTRAL_PROMOTION_APPROVE', 'SP_CENTRAL_PROMOTION_RISK-APPROVE'],
      reject: ['SP_CENTRAL_PROMOTION_APPROVE', 'SP_CENTRAL_PROMOTION_RISK-APPROVE'],
    },
  },
  audits: {
    auditName: 'pandora-audits',
    writeTimeout: 500,
  },
  navigation: {
    closed: true,
    expanded: false,
    menu: [
      {
        id: 'promotions',
        label: 'Campañas',
        icon: 'fatag',
        expanded: false,
        items: [
          {
            id: 'list',
            label: 'Listado de campañas',
            link: '/promotions/list',
          },
          {
            id: 'createcampaign',
            label: 'Crear campaña',
            link: '/promotions/create',
          },
          {
            id: 'statusdraft',
            label: 'Borradores',
            link: '/',
          },
          {
            id: 'statuspending',
            label: 'Aprobación pendiente',
            link: '/',
          },
        ],
        permissions: {
          roles: [
            'SP_CENTRAL_COM',
            'SP_CENTRAL_MKT',
            'SP_CENTRAL_HEADCOM',
            'SP_CENTRAL_LEAD',
            'SP_CENTRAL_DEV',
            'SP_CENTRAL_FULL',
          ],
        },
      },
      {
        id: 'items',
        label: 'Historial de los items',
        icon: 'faclock',
        link: '/items',
        closed: false,
        expanded: true,
      },
      {
        id: 'credibility',
        label: 'Excepciones de credibilidad',
        icon: 'faban',
        link: '/credibility/exceptions',
        permissions: {
          roles: ['SP_CENTRAL_FULL', 'SP_CENTRAL_DEV', 'SP_CENTRAL_LEAD'],
          strict: false,
        },
      },
      {
        id: 'massiveOffer',
        label: 'Carga de ofertas masivas',
        icon: 'fatag',
        link: '/offers/massive',
        permissions: {
          roles: ['SP_CENTRAL_FULL', 'SP_CENTRAL_DEV', 'SP_CENTRAL_LEAD'],
          strict: false,
        },
      },
      {
        id: 'exhibition',
        label: 'Exposición',
        icon: 'FaRegObjectGroup',
        link: '/v2/exhibition/containers',
        closed: true,
        permissions: {
          roles: ['SP_CENTRAL_DEV', 'SP_CENTRAL_FULL'],
          strict: false,
        },
      },
      {
        id: 'support',
        label: 'Soporte',
        icon: 'faquestioncircle',
        link: '/tickets',
        permissions: {
          roles: [
            'SP_CENTRAL_COM',
            'SP_CENTRAL_MKT',
            'SP_CENTRAL_HEADCOM',
            'SP_CENTRAL_LEAD',
            'SP_CENTRAL_DEV',
            'SP_CENTRAL_FULL',
          ],
          strict: false,
        },
        expanded: true,
      },
    ],
  },
};
